# Generated by Django 5.1.3 on 2024-11-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='caracteristicas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
