# Generated by Django 5.1.3 on 2024-12-08 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0003_empresa_inmueble_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('ci', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='inmuebleslist_app.empresa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesado', to='inmuebleslist_app.persona')),
            ],
        ),
    ]
